
name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
      deploy-dev:
      runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      - uses: action/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ sercret.SSH_Host *ip da instancia}}
          username: ${{ secrets.SSH_USER *user do app}}  
          port: ${{ secrets.SSH_PORT}}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules*copia todo o projeto e ignora pasta node"
          target: "test"

      - name: Update API
        uses: appleboy/scp-action@master
        with:
          host: ${{ sercret.SSH_Host *ip da instancia}}
          username: ${{ secrets.SSH_USER *user do app}}  
          port: ${{ secrets.SSH_PORT}}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules*copia todo o projeto e ignora pasta node"
          target: |
            cd ~/app/api-rentx
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api


   
